---
  development:
    MSG_KEY: skAW9SNdivT5PW9AM7JkMSkKra5Tc1TnaZFJukm1Gyc=
    DATABASE_URL: sqlite://app/db/store/development.db
    DB_KEY: AZYdc/9IWdXYiISS20G030PnB0CYCJKBT/Fm4C28rkQ=
    SECURE_SCHEME: HTTP
    SIGNING_KEY: PV5YWAN2gLiTYzAlTsN6OMVJGFO5042qUVx88e6lYjM=
    VERIFY_KEY: YSCTeSCcGi6LRr5flXdOd2Vsh+sURl/KePaaLyQ1u+s=
    SENDGRID_API_KEY: <provision new API key on SendGrid>
    SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
    SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
    API_HOST: http://localhost:3000
    GITHUB_ACCOUNT_URL: https://api.github.com/user
  
  test:
    MSG_KEY: skAW9SNdivT5PW9AM7JkMSkKra5Tc1TnaZFJukm1Gyc=
    DATABASE_URL: sqlite://app/db/store/test.db
    DB_KEY: 1gry0rUSff40rXVtp+cZ4wbNX3LMzpKTcgX8vnZdUlM=
    SECURE_SCHEME: HTTP
    SIGNING_KEY: PV5YWAN2gLiTYzAlTsN6OMVJGFO5042qUVx88e6lYjM=
    VERIFY_KEY: YSCTeSCcGi6LRr5flXdOd2Vsh+sURl/KePaaLyQ1u+s=
    SENDGRID_API_KEY: <provision new API key on SendGrid>
    SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
    SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
    API_HOST: http://localhost:3000
    GITHUB_ACCOUNT_URL: https://api.github.com/user

  production:
    MSG_KEY: <`rake new_key:msg`>
    DB_KEY: dGx/XoV8YBp7cHSS0KHjFKLTZXRo7PR2PrRcXAfIK6A= (run on terminal <`rake new_key:db`>)
    DATABASE_URL: <do not edit - allow production server to set>
    SIGNING_KEY: <`rake newkey:signing`> # needed by client app; used in api tests
    VERIFY_KEY: <`rake newkey:signing`>
    SENDGRID_API_KEY: <provision new API key on SendGrid>
    SENDGRID_API_URL: https://api.sendgrid.com/v3/mail/send
    SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
    SECURE_SCHEME: HTTPS
    GITHUB_ACCOUNT_URL: https://api.github.com/user